# 第三方平台Oauth2授权登录配置
Oauth:
  WechatSignSwitch: false
  WechatOAuth2AppKey:
  WechatOAuth2AppSecret:
  WeiboSignSwitch: false
  WeiboOAuth2AppKey:
  WeiboOAuth2AppSecret:
  QQSignSwitch: false
  QQOAuth2AppKey:
  QQOAuth2AppSecret:
