# Cors配置
Cors:
  AllowAllOrigins: false      #AllowAllOrigins设置是否允许所有来源
  AllowOrigins:               #AllowOrigins设置的地址是可以被执行的跨域请求来源。如果特殊值(*)出现在列表中,所有的跨域将被允许，它是一个列表
    - http://localhost:3000
  AllowMethods:               #AllowMethods 设置客户端允许使用的跨域请求的方法列表，如不设置默认值是简单方法(GET and POST)，它是一个列表
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - HEAD
    - OPTIONS
  AllowHeaders:               #AllowHeaders 设置客户端允许使用的非简单跨域请求的请求头字段，它是一个列表
    - Origin
    - Authorization
    - Content-Length
    - Content-Type
  AllowCredentials: true         # AllowCredentials 显示请求可以包含用户凭证，如cookies,HTTP authentication或客户端SSL证书。它是一个布尔值
  ExposeHeaders:                 # ExposedHeaders指示哪些头可以安全地公开给CORS API，它是一个列表
    - Content-Length
  MaxAge: 3600                   # MaxAge指示可以缓存预检请求的结果的时间（秒）
  #AllowWildcard: true           #是否允许添加源，如http://some domain/*、https://api.*或http://some.*.subdomain.com
  #AllowBrowserExtensions: true  #允许使用流行的浏览器扩展模式
  #AllowWebSockets: true         # 设置允许websocket协议
