# 七牛云对象存储配置
QiniuOss:
  Switch: false
  AccessKey: "yourAccessKey"
  SecretKey: "yourSecretKey"
  Bucket: "yourBucketName"
  UseHTTPS: false                       #是否使用https域名
  UseCdnDomains: false                  #上传是否使用CDN上传加速
  UpTokenExpires: 7200                  #上传凭证2小时有效期
  CallbackURL: ""                       #上传回调地址
  CallbackBodyType: "application/json"  #上传回调信息格式
  EndUser: ""                           #唯一宿主标识
  FsizeMin: 1024                        #限定上传文件大小最小值，单位Byte。
  FsizeLimit: 10485760                  #限定上传文件大小最大值，单位Byte。超过限制上传文件大小的最大值会被判为上传失败，返回 413 状态码。
  MimeLimit: "image/jpeg;image/png;image/gif"  #限定上传类型
