// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test_grpc.proto

package test_grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TestGetUserRequestMessage struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestGetUserRequestMessage) Reset()         { *m = TestGetUserRequestMessage{} }
func (m *TestGetUserRequestMessage) String() string { return proto.CompactTextString(m) }
func (*TestGetUserRequestMessage) ProtoMessage()    {}
func (*TestGetUserRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_grpc_6266cba74ca81776, []int{0}
}
func (m *TestGetUserRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestGetUserRequestMessage.Unmarshal(m, b)
}
func (m *TestGetUserRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestGetUserRequestMessage.Marshal(b, m, deterministic)
}
func (dst *TestGetUserRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestGetUserRequestMessage.Merge(dst, src)
}
func (m *TestGetUserRequestMessage) XXX_Size() int {
	return xxx_messageInfo_TestGetUserRequestMessage.Size(m)
}
func (m *TestGetUserRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TestGetUserRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TestGetUserRequestMessage proto.InternalMessageInfo

func (m *TestGetUserRequestMessage) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type TestGetUserResponseMessage struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestGetUserResponseMessage) Reset()         { *m = TestGetUserResponseMessage{} }
func (m *TestGetUserResponseMessage) String() string { return proto.CompactTextString(m) }
func (*TestGetUserResponseMessage) ProtoMessage()    {}
func (*TestGetUserResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_grpc_6266cba74ca81776, []int{1}
}
func (m *TestGetUserResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestGetUserResponseMessage.Unmarshal(m, b)
}
func (m *TestGetUserResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestGetUserResponseMessage.Marshal(b, m, deterministic)
}
func (dst *TestGetUserResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestGetUserResponseMessage.Merge(dst, src)
}
func (m *TestGetUserResponseMessage) XXX_Size() int {
	return xxx_messageInfo_TestGetUserResponseMessage.Size(m)
}
func (m *TestGetUserResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TestGetUserResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TestGetUserResponseMessage proto.InternalMessageInfo

func (m *TestGetUserResponseMessage) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TestGetUserResponseMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type TestSetUserRequestMessage struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestSetUserRequestMessage) Reset()         { *m = TestSetUserRequestMessage{} }
func (m *TestSetUserRequestMessage) String() string { return proto.CompactTextString(m) }
func (*TestSetUserRequestMessage) ProtoMessage()    {}
func (*TestSetUserRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_grpc_6266cba74ca81776, []int{2}
}
func (m *TestSetUserRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestSetUserRequestMessage.Unmarshal(m, b)
}
func (m *TestSetUserRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestSetUserRequestMessage.Marshal(b, m, deterministic)
}
func (dst *TestSetUserRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestSetUserRequestMessage.Merge(dst, src)
}
func (m *TestSetUserRequestMessage) XXX_Size() int {
	return xxx_messageInfo_TestSetUserRequestMessage.Size(m)
}
func (m *TestSetUserRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TestSetUserRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TestSetUserRequestMessage proto.InternalMessageInfo

func (m *TestSetUserRequestMessage) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TestSetUserRequestMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type TestSetUserResponseMessage struct {
	Result               bool     `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestSetUserResponseMessage) Reset()         { *m = TestSetUserResponseMessage{} }
func (m *TestSetUserResponseMessage) String() string { return proto.CompactTextString(m) }
func (*TestSetUserResponseMessage) ProtoMessage()    {}
func (*TestSetUserResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_grpc_6266cba74ca81776, []int{3}
}
func (m *TestSetUserResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestSetUserResponseMessage.Unmarshal(m, b)
}
func (m *TestSetUserResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestSetUserResponseMessage.Marshal(b, m, deterministic)
}
func (dst *TestSetUserResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestSetUserResponseMessage.Merge(dst, src)
}
func (m *TestSetUserResponseMessage) XXX_Size() int {
	return xxx_messageInfo_TestSetUserResponseMessage.Size(m)
}
func (m *TestSetUserResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TestSetUserResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TestSetUserResponseMessage proto.InternalMessageInfo

func (m *TestSetUserResponseMessage) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type TestEmptyReqMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestEmptyReqMessage) Reset()         { *m = TestEmptyReqMessage{} }
func (m *TestEmptyReqMessage) String() string { return proto.CompactTextString(m) }
func (*TestEmptyReqMessage) ProtoMessage()    {}
func (*TestEmptyReqMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_grpc_6266cba74ca81776, []int{4}
}
func (m *TestEmptyReqMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestEmptyReqMessage.Unmarshal(m, b)
}
func (m *TestEmptyReqMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestEmptyReqMessage.Marshal(b, m, deterministic)
}
func (dst *TestEmptyReqMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestEmptyReqMessage.Merge(dst, src)
}
func (m *TestEmptyReqMessage) XXX_Size() int {
	return xxx_messageInfo_TestEmptyReqMessage.Size(m)
}
func (m *TestEmptyReqMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TestEmptyReqMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TestEmptyReqMessage proto.InternalMessageInfo

type TestStreamMessage struct {
	Bit                  int64    `protobuf:"varint,1,opt,name=bit" json:"bit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestStreamMessage) Reset()         { *m = TestStreamMessage{} }
func (m *TestStreamMessage) String() string { return proto.CompactTextString(m) }
func (*TestStreamMessage) ProtoMessage()    {}
func (*TestStreamMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_grpc_6266cba74ca81776, []int{5}
}
func (m *TestStreamMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestStreamMessage.Unmarshal(m, b)
}
func (m *TestStreamMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestStreamMessage.Marshal(b, m, deterministic)
}
func (dst *TestStreamMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestStreamMessage.Merge(dst, src)
}
func (m *TestStreamMessage) XXX_Size() int {
	return xxx_messageInfo_TestStreamMessage.Size(m)
}
func (m *TestStreamMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TestStreamMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TestStreamMessage proto.InternalMessageInfo

func (m *TestStreamMessage) GetBit() int64 {
	if m != nil {
		return m.Bit
	}
	return 0
}

func init() {
	proto.RegisterType((*TestGetUserRequestMessage)(nil), "TestGetUserRequestMessage")
	proto.RegisterType((*TestGetUserResponseMessage)(nil), "TestGetUserResponseMessage")
	proto.RegisterType((*TestSetUserRequestMessage)(nil), "TestSetUserRequestMessage")
	proto.RegisterType((*TestSetUserResponseMessage)(nil), "TestSetUserResponseMessage")
	proto.RegisterType((*TestEmptyReqMessage)(nil), "TestEmptyReqMessage")
	proto.RegisterType((*TestStreamMessage)(nil), "TestStreamMessage")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TestRpcServiceClient is the client API for TestRpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TestRpcServiceClient interface {
	GetUser(ctx context.Context, in *TestGetUserRequestMessage, opts ...grpc.CallOption) (*TestGetUserResponseMessage, error)
	SetUser(ctx context.Context, in *TestSetUserRequestMessage, opts ...grpc.CallOption) (*TestSetUserResponseMessage, error)
	SendSome(ctx context.Context, in *TestEmptyReqMessage, opts ...grpc.CallOption) (TestRpcService_SendSomeClient, error)
}

type testRpcServiceClient struct {
	cc *grpc.ClientConn
}

func NewTestRpcServiceClient(cc *grpc.ClientConn) TestRpcServiceClient {
	return &testRpcServiceClient{cc}
}

func (c *testRpcServiceClient) GetUser(ctx context.Context, in *TestGetUserRequestMessage, opts ...grpc.CallOption) (*TestGetUserResponseMessage, error) {
	out := new(TestGetUserResponseMessage)
	err := c.cc.Invoke(ctx, "/TestRpcService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testRpcServiceClient) SetUser(ctx context.Context, in *TestSetUserRequestMessage, opts ...grpc.CallOption) (*TestSetUserResponseMessage, error) {
	out := new(TestSetUserResponseMessage)
	err := c.cc.Invoke(ctx, "/TestRpcService/SetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testRpcServiceClient) SendSome(ctx context.Context, in *TestEmptyReqMessage, opts ...grpc.CallOption) (TestRpcService_SendSomeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TestRpcService_serviceDesc.Streams[0], "/TestRpcService/SendSome", opts...)
	if err != nil {
		return nil, err
	}
	x := &testRpcServiceSendSomeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TestRpcService_SendSomeClient interface {
	Recv() (*TestStreamMessage, error)
	grpc.ClientStream
}

type testRpcServiceSendSomeClient struct {
	grpc.ClientStream
}

func (x *testRpcServiceSendSomeClient) Recv() (*TestStreamMessage, error) {
	m := new(TestStreamMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TestRpcServiceServer is the server API for TestRpcService service.
type TestRpcServiceServer interface {
	GetUser(context.Context, *TestGetUserRequestMessage) (*TestGetUserResponseMessage, error)
	SetUser(context.Context, *TestSetUserRequestMessage) (*TestSetUserResponseMessage, error)
	SendSome(*TestEmptyReqMessage, TestRpcService_SendSomeServer) error
}

func RegisterTestRpcServiceServer(s *grpc.Server, srv TestRpcServiceServer) {
	s.RegisterService(&_TestRpcService_serviceDesc, srv)
}

func _TestRpcService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestGetUserRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestRpcServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TestRpcService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestRpcServiceServer).GetUser(ctx, req.(*TestGetUserRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestRpcService_SetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestSetUserRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestRpcServiceServer).SetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TestRpcService/SetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestRpcServiceServer).SetUser(ctx, req.(*TestSetUserRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestRpcService_SendSome_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TestEmptyReqMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TestRpcServiceServer).SendSome(m, &testRpcServiceSendSomeServer{stream})
}

type TestRpcService_SendSomeServer interface {
	Send(*TestStreamMessage) error
	grpc.ServerStream
}

type testRpcServiceSendSomeServer struct {
	grpc.ServerStream
}

func (x *testRpcServiceSendSomeServer) Send(m *TestStreamMessage) error {
	return x.ServerStream.SendMsg(m)
}

var _TestRpcService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "TestRpcService",
	HandlerType: (*TestRpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _TestRpcService_GetUser_Handler,
		},
		{
			MethodName: "SetUser",
			Handler:    _TestRpcService_SetUser_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendSome",
			Handler:       _TestRpcService_SendSome_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "test_grpc.proto",
}

func init() { proto.RegisterFile("test_grpc.proto", fileDescriptor_test_grpc_6266cba74ca81776) }

var fileDescriptor_test_grpc_6266cba74ca81776 = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xd9, 0x54, 0xda, 0x3a, 0x87, 0xaa, 0xeb, 0x1f, 0x6a, 0xbc, 0x94, 0x05, 0xa1, 0x20,
	0x2c, 0xa2, 0xe2, 0x55, 0x29, 0x88, 0x27, 0x2f, 0xbb, 0x7a, 0x96, 0x34, 0x19, 0x4a, 0xc0, 0x24,
	0xdb, 0x9d, 0xa9, 0xe0, 0xb7, 0xf4, 0x23, 0x49, 0xd2, 0xf5, 0x50, 0x4c, 0x82, 0xb7, 0x59, 0x78,
	0xfb, 0x9b, 0xf7, 0xde, 0xc0, 0x01, 0x23, 0xf1, 0xfb, 0xca, 0xbb, 0x54, 0x3b, 0x5f, 0x71, 0xa5,
	0xae, 0xe0, 0xfc, 0x15, 0x89, 0x9f, 0x91, 0xdf, 0x08, 0xbd, 0xc1, 0xf5, 0x06, 0x89, 0x5f, 0x90,
	0x28, 0x59, 0xa1, 0x9c, 0x40, 0x94, 0x67, 0x53, 0x31, 0x13, 0xf3, 0x81, 0x89, 0xf2, 0x4c, 0x3d,
	0x42, 0xbc, 0x23, 0x26, 0x57, 0x95, 0x84, 0x1d, 0x6a, 0x29, 0x61, 0xaf, 0x4c, 0x0a, 0x9c, 0x46,
	0x33, 0x31, 0xdf, 0x37, 0xcd, 0xac, 0x1e, 0xb6, 0xeb, 0xec, 0x7f, 0xd6, 0xb5, 0x02, 0xee, 0xb6,
	0x16, 0x6c, 0xbb, 0x85, 0x33, 0x18, 0x7a, 0xa4, 0xcd, 0x07, 0x37, 0x94, 0xb1, 0x09, 0x2f, 0x75,
	0x0a, 0xc7, 0xf5, 0xaf, 0xa7, 0xc2, 0xf1, 0x97, 0xc1, 0x75, 0x90, 0xab, 0x4b, 0x38, 0x6a, 0x60,
	0xec, 0x31, 0x29, 0x7e, 0x19, 0x87, 0x30, 0x58, 0xe6, 0x1c, 0x6c, 0xd4, 0xe3, 0xcd, 0xb7, 0x80,
	0x49, 0xad, 0x33, 0x2e, 0xb5, 0xe8, 0x3f, 0xf3, 0x14, 0xe5, 0x02, 0x46, 0xa1, 0x05, 0x19, 0xeb,
	0xce, 0x02, 0xe3, 0x0b, 0xdd, 0xd3, 0xd7, 0x02, 0x46, 0x76, 0x87, 0x61, 0x7b, 0x18, 0x1d, 0x81,
	0xef, 0x61, 0x6c, 0xb1, 0xcc, 0x6c, 0x55, 0xa0, 0x3c, 0xd1, 0x2d, 0x19, 0x63, 0xa9, 0xff, 0x44,
	0xbc, 0x16, 0xcb, 0x61, 0x73, 0xfd, 0xdb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x36, 0x0a,
	0x03, 0x10, 0x02, 0x00, 0x00,
}
